apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: spectacular-takin-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-hub/spectacular-takin-java-quarkus-gitops